### ISSUE TITLE
AttributeError: 'ImageDraw' object has no attribute 'textsize'

### ISSUE THREAD

**Issue by trinv** [trinv/PowerDNS#4]
```
Jul  5 18:06:26 nameserver1 gunicorn[5834]:     image_data = self.image_generator.generate(answer)
Jul  5 18:06:26 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/captcha/image.py", line 45, in generate
Jul  5 18:06:26 nameserver1 gunicorn[5834]:     im = self.generate_image(chars)
Jul  5 18:06:26 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/captcha/image.py", line 228, in generate_image
Jul  5 18:06:26 nameserver1 gunicorn[5834]:     im = self.create_captcha_image(chars, color, background)
Jul  5 18:06:26 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/captcha/image.py", line 198, in create_captcha_image
Jul  5 18:06:26 nameserver1 gunicorn[5834]:     images.append(_draw_character(" "))
Jul  5 18:06:26 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/captcha/image.py", line 165, in _draw_character
Jul  5 18:06:26 nameserver1 gunicorn[5834]:     w, h = draw.textsize(c, font=font)
Jul  5 18:06:26 nameserver1 gunicorn[5834]: AttributeError: 'ImageDraw' object has no attribute 'textsize'
Jul  5 18:07:21 nameserver1 gunicorn[5834]: [2023-07-05 18:07:21,392] [app.py:1449] ERROR - Exception on /register [GET]
Jul  5 18:07:21 nameserver1 gunicorn[5834]: Traceback (most recent call last):
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     response = self.full_dispatch_request()
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     rv = self.handle_user_exception(e)
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     rv = self.dispatch_request()
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/index.py", line 781, in register
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     return render_template('register.html', captcha_enable=CAPTCHA_ENABLE)
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/templating.py", line 154, in render_template
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     return _render(
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     rv = template.render(context)
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     self.environment.handle_exception()
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     raise rewrite_traceback_stack(source=source)
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/powerdnsadmin/templates/register.html", line 160, in top-level template code
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     {{ captcha() }}
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask_session_captcha/__init__.py", line 39, in _generate
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     base64_captcha = self.generate()
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask_session_captcha/__init__.py", line 69, in generate
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     image_data = self.image_generator.generate(answer)
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/captcha/image.py", line 45, in generate
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     im = self.generate_image(chars)
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/captcha/image.py", line 228, in generate_image
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     im = self.create_captcha_image(chars, color, background)
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/captcha/image.py", line 198, in create_captcha_image
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     images.append(_draw_character(" "))
Jul  5 18:07:21 nameserver1 gunicorn[5834]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/captcha/image.py", line 165, in _draw_character
Jul  5 18:07:21 nameserver1 gunicorn[5834]:     w, h = draw.textsize(c, font=font)
Jul  5 18:07:21 nameserver1 gunicorn[5834]: AttributeError: 'ImageDraw' object has no attribute 'textsize'
```

**Comment by trinv** [comment]
```
pip3 install Pillow==10.0.0

```
